defaults: &defaults
  password_reset_email_sender: pwd-reset@intersect.org.au
  account_request_user_status_email_sender: account-status@intersect.org.au
  account_request_admin_notification_sender: account-request@intersect.org.au
  papyrus_access_request_email_sender: papyrus-access-request@intersect.org.au
  number_of_papyri_per_page: 20
  image_root: /tmp

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

qa:
  <<: *defaults
  image_root: /home/devel/images

staging:
  <<: *defaults
  image_root: /home/devel/images

jenkins:
  <<: *defaults
