defaults: &defaults
  password_reset_email_sender: pwd-reset@intersect.org.au
  papyrus_access_request_email_sender: papyrus-access-request@intersect.org.au
  number_of_papyri_per_page: 20
  number_of_one_ids_per_page: 20
  image_root: /tmp
  one_id_password_reset_url: http://mypassword.mq.edu.au
  papyrus_created_email_sender: papyrus-account-created@intersect.org.au
  account_contact: contactme@example.com
  rifcs_collection_location_email: somebody-maybethesameasabove@example.com
  oai_admin_email: oai_admin@example.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

qa:
  <<: *defaults
  image_root: /home/devel/images

staging:
  <<: *defaults
  image_root: /home/devel/images

jenkins:
  <<: *defaults

showcase:
  <<: *defaults
