defaults: &defaults
  host: localhost
  port: 54321
  base: OU=Active,OU=MQ-Users,DC=mqauth,DC=uni,DC=mq,DC=edu,DC=au
  admin_user: admin
  admin_password: adminpassword
  one_id_key: uid

development:
  <<: *defaults
  port: 3897

test:
  <<: *defaults
