development:
  host: localhost
  base: OU=Active,OU=MQ-Users,DC=mqauth,DC=uni,DC=mq,DC=edu,DC=au
  admin_user: admin
  admin_password: adminpassword
  one_id_key: uid
  port: 3897

test:
  host: localhost
  base: OU=Active,OU=MQ-Users,DC=mqauth,DC=uni,DC=mq,DC=edu,DC=au
  admin_user: admin
  admin_password: adminpassword
  one_id_key: uid
  port: 54321
